# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 904b964cb131004377fbc577279f0ab95b92daa7d1c06717487a66678b95b37dd0c93fe1ad4ec9c4abc7dfd81291ebd711de9379d2a0fcc327a06ad220184716

test:
  secret_key_base: 16d49524d9be159ba0d24ba9ee3d82106c285449430db9e9e5ae24e5b5d55eb48c3fec8c06e3cb7206e35fb2aee3f42614850b30bc6a147256168fc8fdb9a5bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
